services:
  web:
    build: .
    image: vpn-api:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vpn
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
