"""expand models add vpn_peers payments

Revision ID: 881faf8bfb76
Revises: init
Create Date: autogenerated
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "881faf8bfb76"
down_revision = "init"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("tariffs", sa.Column("description", sa.String(), nullable=True))
    op.add_column("tariffs", sa.Column("duration_days", sa.Integer(), nullable=False))
    op.add_column(
        "tariffs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    with op.batch_alter_table("tariffs") as batch_op:
        batch_op.alter_column(
            "price", existing_type=sa.INTEGER(), type_=sa.Numeric(10, 2), existing_nullable=False
        )

    op.add_column("user_tariffs", sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "user_tariffs", sa.Column("status", sa.String(), nullable=False, server_default="active")
    )
    with op.batch_alter_table("user_tariffs") as batch_op:
        batch_op.alter_column(
            "started_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
            nullable=False,
        )
        batch_op.create_unique_constraint(
            "uix_user_tariff_start", ["user_id", "tariff_id", "started_at"]
        )

    # Add google_id; other user columns (status, is_admin, created_at) were
    # already created in the initial migration and must not be re-added here.
    op.add_column("users", sa.Column("google_id", sa.String(), nullable=True))

    op.create_table(
        "vpn_peers",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("wg_private_key", sa.String(), nullable=False),
        sa.Column("wg_public_key", sa.String(), nullable=False),
        sa.Column("wg_ip", sa.String(), nullable=False),
        sa.Column("allowed_ips", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=True
        ),
        sa.Column("amount", sa.Numeric(10, 2), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False, server_default="USD"),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("provider_payment_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("vpn_peers")

    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("created_at")
        batch_op.drop_column("is_admin")
        batch_op.drop_column("status")
        batch_op.drop_column("google_id")

    with op.batch_alter_table("user_tariffs") as batch_op:
        batch_op.drop_constraint("uix_user_tariff_start", type_="unique")
        batch_op.drop_column("status")
        batch_op.drop_column("ended_at")
        batch_op.alter_column(
            "started_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            nullable=True,
        )

    with op.batch_alter_table("tariffs") as batch_op:
        batch_op.alter_column(
            "price", existing_type=sa.Numeric(10, 2), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("duration_days")
        batch_op.drop_column("description")
    # ### end Alembic commands ###
