name: CI & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Install runtime and dev dependencies using the interpreter's pip to avoid PATH surprises
          python -m pip install -r vpn_api/requirements.txt
          # Ensure dev dependencies are always installed so pytest and test helpers are available
          python -m pip install -r vpn_api/requirements-dev.txt
      - name: Debug test environment
        run: |
          echo "--- python and pytest info ---"
          python -V || true
          python -m pip show pytest || true
          echo "--- env vars ---"
          python - <<'PY'
import os
print('DEV_INIT_DB=', os.environ.get('DEV_INIT_DB'))
print('DATABASE_URL=', os.environ.get('DATABASE_URL'))
print('PWD=', os.getcwd())
PY
          echo "--- vpn_api dir listing ---"
          ls -la vpn_api || true
          echo "--- conftest.py preview ---"
          sed -n '1,200p' vpn_api/conftest.py || true
      - name: Run tests
        run: |
          # run pytest via the interpreter to guarantee the correct executable is used
          python -m pytest -q

      - name: Post-install diagnostics
        run: |
          echo "--- pip list ---"
          python -m pip list
          echo "--- pytest via python -m pytest --version ---"
          python -m pytest --version || true

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Create DB backup (pg_dump)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "Installing pg_dump (postgresql-client)"
          sudo apt-get update && sudo apt-get install -y postgresql-client
          echo "Creating database backup before deploy"
          # Use libpq connection string support in pg_dump
          pg_dump --dbname="${DATABASE_URL}" -Fc -f backup.dump
          echo "Backup written to backup.dump"
      - name: Upload DB backup as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pre-deploy-backup
          path: backup.dump
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Rsync files to server
        run: |
          rsync -avz --delete --exclude '.git' --exclude 'venv' ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
      - name: SSH run migrations on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && docker compose run --rm -v $(pwd):/app web alembic -c /app/alembic.ini upgrade head || true"
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
      - name: SSH run remote deploy (docker compose)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && docker compose pull || true && docker compose up -d --build"
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
