name: Container image security scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    name: Build & scan Docker image with Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local tag)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: vpn-api:local

      - name: Scan image with Trivy (docker run)
        run: |
          # pull the official trivy image and scan the locally built image
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasecurity/trivy:0.44.0 image --format table --exit-code 1 --vuln-type os,library vpn-api:local
