name: Container image security scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    name: Build & scan Docker image with Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local tag)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: vpn-api:local

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: vpn-api:local
          format: table
          exit-code: '1'
          vuln-type: 'os,library'
          ignore-unfixed: false
